---
# Regex capture all rule names:               (?<=[#]{2}\n\s\s)(.*)(?=:)
# Regex capture all rule options:             (?<=[#]{4}\n)([^#]*)(?=\n\s+\#\#)

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

env:
  browser: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  ##
  array-bracket-spacing:
  ####
    - error
    - never

  ##
  array-bracket-newline:
  ####
    - error
    - multiline: true
      minItems: null

  ##
  camelcase:
  ####
    - error
    - properties: always

  ##
  comma-dangle:
  ####
    - error
    - always-multiline

  ##
  comma-spacing:
  ####
    - error
    - before: false
      after: true

  ##
  dot-location:
  ####
    - error
    - property

  ##
  eqeqeq:
  ####
    - error
    - always

  ##
  func-call-spacing:
  ####
    - error
    - never

  ##
  func-name-matching:
  ####
    - error
    - always

  ##
  func-names:
  ####
    - error
    - always

  ##
  indent:
  ####
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: 1

  ##
  key-spacing:
  ####
    - error
    - singleLine:
        mode: strict
        beforeColon: false
        afterColon: true
      multiLine:
        beforeColon: true
        afterColon: true
        align: colon

  ##
  keyword-spacing:
  ####
    - error
    - before: true
      after: true

  ##
  no-eval:
  ####
    - error

  ##
  no-floating-decimal:
  ####
    - error

  ##
  no-underscore-dangle:
  ####
    - error
    - allowAfterThis: true
      allowAfterSuper: true

  ##
  no-whitespace-before-property:
  ####
    - error

  ##
  object-curly-spacing:
  ####
    - error
    - always
    - arraysInObjects: true
      objectsInObjects: true

  ##
  one-var:
  ####
    - error
    - uninitialized: always
      initialized: never

  ##
  one-var-declaration-per-line:
  ####
    - error
    - initializations

  ##
  operator-linebreak:
  ####
    - error
    - before

  ##
  require-jsdoc:
  ####
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: false

  ##
  semi:
  ####
    - error
    - always

  ##
  semi-spacing:
  ####
    - error
    - before: false
      after: true

  ##
  semi-style:
  ####
    - error
    - last

  ##
  space-before-blocks:
  ####
    - error
    - functions: always
      keywords: always
      classes: always

  ##
  space-before-function-paren:
  ####
    - error
    - never

  ##
  space-in-parens:
  ####
    - error
    - never

  ##
  space-unary-ops:
  ####
    - error
    - words: true
      nonwords: false
      overrides:
        "!": true

  ##
  switch-colon-spacing:
  ####
    - error
    - before: false
      after: true

  ##
  wrap-iife:
  ####
    - error
    - outside